site_name: GCSEs for Dads
docs_dir: content
site_url: https://gcsesfordads.uk/
site_dir: docs

theme:
  name: material
  custom_dir: overrides

nav:
  - Home: index.md
  - Physics:
      - Example Physics Page: physics-k7m4/physics2-electricity.md

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - tables

extra:
  generator: false
  social: []

hooks: []