site_name: GCSEs for Dads
docs_dir: content
site_url: https://gcsesfordads.uk/
site_dir: site

theme:
  name: material
  custom_dir: overrides

nav:
  - Home: index.md
  - Free Examples:
      - Science (Combined): demo/index.md

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - tables

extra:
  generator: false
  social: []

hooks: []