site_name: GCSEs for Dads

theme:
  name: material

nav:
  - Home: index.md
  - Physics:
      - Physics 1: physics/physics1-energy.md
      - Physics 2: physics/physics2-electricity.md
      - Physics 3: physics/physics3-particle-model-of-matter.md
      - Physics 4: physics/physics4-atomic-structure-and-radiation.md
      - Physics 5: physics/physics5-forces.md
      - Physics 6: physics/physics6-waves.md
      - Physics 7: physics/physics7-magnetism-and-electromagnetism.md
      - Physics 8: physics/physics8-space-physics.md